
include_guard(GLOBAL)
gvk_enable_module(gvk-command-structures)
gvk_enable_module(gvk-containers)
gvk_enable_module(gvk-cppgen)
gvk_enable_module(gvk-handles)
gvk_enable_module(gvk-layer)
gvk_enable_module(gvk-python)
gvk_enable_module(gvk-reference)
gvk_enable_module(gvk-runtime)
gvk_enable_module(gvk-structures)
gvk_enable_external_module(boost-multiprecision)
