
################################################################################
# gvk-pipeline-explorer-backend
gvk_add_static_library(
    TARGET
        gvk-pipeline-explorer-backend
    FOLDER
        "gvk-pipeline-explorer/"
    LINK_LIBRARIES
        gvk-command-structures
        gvk-containers
        gvk-handles
        gvk-layer
        gvk-pipeline-explorer-info
        gvk-pipeline-explorer-plugin-factory
        gvk-reference
        gvk-runtime
        gvk-spirv
        gvk-structures
        gvk-system
        boost-asio
        boost-multiprecision
        stb
        Threads::Threads
    INCLUDE_DIRECTORIES
        "${generatedIncludeDirectory}"
        "${includeDirectory}"
    INCLUDE_FILES
        "${backendGeneratedIncludeFiles}"
        "${includePath}/backend/query-managers/command-collection-request-manager.hpp"
        "${includePath}/backend/query-managers/performance-query-manager.hpp"
        "${includePath}/backend/query-managers/pipeline-statistics-query-manager.hpp"
        "${includePath}/backend/query-managers/query-manager.hpp"
        "${includePath}/backend/query-managers/timeline-query-manager.hpp"
        "${includePath}/backend/query-managers/timestamp-query-manager.hpp"
        "${includePath}/backend/cmd-tracker.hpp"
        "${includePath}/backend/device-address-tracker.hpp"
        "${includePath}/backend/handle-info.hpp"
        "${includePath}/backend/ipc-messenger.hpp"
        "${includePath}/backend/pipeline-explorer.hpp"
        "${includePath}/backend/tool-dispatch-manager.hpp"
        "${includePath}/backend/tool.hpp"
        "${includePath}/backend/utilities.hpp"
    SOURCE_FILES
        "${backendGeneratedSourceFiles}"
        "${sourcePath}/backend/query-managers/command-collection-request-manager.cpp"
        "${sourcePath}/backend/query-managers/performance-query-manager.cpp"
        "${sourcePath}/backend/query-managers/pipeline-statistics-query-manager.cpp"
        "${sourcePath}/backend/query-managers/query-manager.cpp"
        "${sourcePath}/backend/query-managers/timeline-query-manager.cpp"
        "${sourcePath}/backend/query-managers/timestamp-query-manager.cpp"
        "${sourcePath}/backend/buffer.cpp"
        "${sourcePath}/backend/cmd-tracker.cpp"
        "${sourcePath}/backend/command-buffer.cpp"
        "${sourcePath}/backend/descriptor-set-layout.cpp"
        "${sourcePath}/backend/device-memory.cpp"
        "${sourcePath}/backend/device-address-tracker.cpp"
        "${sourcePath}/backend/device.cpp"
        "${sourcePath}/backend/instance.cpp"
        "${sourcePath}/backend/ipc-messenger.cpp"
        "${sourcePath}/backend/pipeline-layout.cpp"
        "${sourcePath}/backend/pipeline.cpp"
        "${sourcePath}/backend/pipeline-explorer.cpp"
        "${sourcePath}/backend/queue.cpp"
        "${sourcePath}/backend/render-pass.cpp"
        "${sourcePath}/backend/sampler.cpp"
        "${sourcePath}/backend/shader-module.cpp"
        "${sourcePath}/backend/tool-dispatch-manager.cpp"
        "${sourcePath}/backend/tool.cpp"
        "${sourcePath}/backend/utilities.cpp"
)
