
include_guard(GLOBAL)
gvk_enable_module(gvk-command-structures)
gvk_enable_module(gvk-cppgen)
gvk_enable_module(gvk-handles)
gvk_enable_module(gvk-layer)
gvk_enable_module(gvk-reference)
gvk_enable_module(gvk-runtime)
gvk_enable_module(gvk-spirv)
if(gvk-build-tests)
    gvk_enable_module(gvk-handles)
    gvk_enable_module(gvk-math)
    gvk_enable_module(gvk-system)
endif()
